name: Deploy to Xserver

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 他のビルドステップがあればここに追加

      - name: Deploy to Xserver
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > deploy_key
          chmod 600 deploy_key
          rsync -avz -e "ssh -i deploy_key -o StrictHostKeyChecking=no" ./ sv14737.xserver.jp@burst.style:/path/to/your/site/on/xserver/
          rm -f deploy_key
