name: Deploy to Xserver

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: ./_site

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: website

      - name: Deploy to Xserver
        run: |
          echo "$DEPLOY_KEY" > deploy_key
          chmod 600 deploy_key
          rsync -avz -e "ssh -i deploy_key -o StrictHostKeyChecking=no" website/ sv14737.xserver.jp@burst.style:/burst.style/public_html
          rm -f deploy_key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}


